import 'app_strings.dart';

/// Supported languages
/// English first, then alphabetical by English name
enum AppLanguage {
  english,
  arabic,
  bengali,
  chinese,
  danish,
  dutch,
  finnish,
  french,
  german,
  greek,
  hebrew,
  hindi,
  indonesian,
  italian,
  japanese,
  korean,
  norwegian,
  polish,
  portuguese,
  romanian,
  russian,
  spanish,
  swedish,
  thai,
  turkish,
  ukrainian,
  vietnamese,
  // Add more languages here as needed
}

/// Localization manager for the app
/// Handles all text translations
class AppLocalizations {
  final AppLanguage language;

  AppLocalizations(this.language);

  /// Get localized string by key
  String translate(String key) {
    switch (language) {
      case AppLanguage.english:
        return _englishStrings[key] ?? key;
      case AppLanguage.arabic:
        return _arabicStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.bengali:
        return _bengaliStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.chinese:
        return _chineseStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.danish:
        return _danishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.dutch:
        return _dutchStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.finnish:
        return _finnishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.french:
        return _frenchStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.german:
        return _germanStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.greek:
        return _greekStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.hebrew:
        return _hebrewStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.hindi:
        return _hindiStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.indonesian:
        return _indonesianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.italian:
        return _italianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.japanese:
        return _japaneseStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.korean:
        return _koreanStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.norwegian:
        return _norwegianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.polish:
        return _polishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.portuguese:
        return _portugueseStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.romanian:
        return _romanianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.russian:
        return _russianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.spanish:
        return _spanishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.swedish:
        return _swedishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.thai:
        return _thaiStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.turkish:
        return _turkishStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.ukrainian:
        return _ukrainianStrings[key] ?? _englishStrings[key] ?? key;
      case AppLanguage.vietnamese:
        return _vietnameseStrings[key] ?? _englishStrings[key] ?? key;
      // Add more language cases here
    }
  }

  /// Convenience getters for common strings
  String get appName => translate(AppStrings.appName);
  String get navHome => translate(AppStrings.navHome);
  String get navScan => translate(AppStrings.navScan);
  String get navHistory => translate(AppStrings.navHistory);
  String get scanMyFridge => translate(AppStrings.scanMyFridge);
  String get lastResult => translate(AppStrings.lastResult);
  String get takePhotosHelper => translate(AppStrings.takePhotosHelper);
  String get uploadFromGallery => translate(AppStrings.uploadFromGallery);
  String get reviewPhotos => translate(AppStrings.reviewPhotos);
  String get tapThumbnailToPreview =>
      translate(AppStrings.tapThumbnailToPreview);
  String get thisIsEnough => translate(AppStrings.thisIsEnough);
  String get addAnotherPhoto => translate(AppStrings.addAnotherPhoto);
  String get confirmIngredients => translate(AppStrings.confirmIngredients);
  String get heresWhatIThink => translate(AppStrings.heresWhatIThink);
  String get mightBeWrong => translate(AppStrings.mightBeWrong);
  String get addSomethingElse => translate(AppStrings.addSomethingElse);
  String get cookWithThis => translate(AppStrings.cookWithThis);
  String get lookingClosely => translate(AppStrings.lookingClosely);
  String get fridgeHasPotential => translate(AppStrings.fridgeHasPotential);
  String get heresWhatYouCanMake => translate(AppStrings.heresWhatYouCanMake);
  String get editIngredients => translate(AppStrings.editIngredients);
  String get scanAgain => translate(AppStrings.scanAgain);
  String get settings => translate(AppStrings.settings);
  String get languageLabel => translate(AppStrings.languageLabel);
  String get selectLanguage => translate(AppStrings.selectLanguage);
  String get clearHistory => translate(AppStrings.clearHistory);
  String get historyCleared => translate(AppStrings.historyCleared);
  String get about => translate(AppStrings.about);
  String get aboutTitle => translate(AppStrings.aboutTitle);
  String get aboutContent => translate(AppStrings.aboutContent);
  String get feedback => translate(AppStrings.feedback);
  String get feedbackComingSoon => translate(AppStrings.feedbackComingSoon);
  String get privacy => translate(AppStrings.privacy);
  String get privacyTitle => translate(AppStrings.privacyTitle);
  String get privacyContent => translate(AppStrings.privacyContent);
  String get ok => translate(AppStrings.ok);
  String get history => translate(AppStrings.history);
  String get emptyHistory => translate(AppStrings.emptyHistory);
  String get share => translate(AppStrings.share);
  String get recipeBadgeFastLazy => translate(AppStrings.recipeBadgeFastLazy);
  String get recipeBadgeActuallyGood =>
      translate(AppStrings.recipeBadgeActuallyGood);
  String get recipeBadgeShouldntWork =>
      translate(AppStrings.recipeBadgeShouldntWork);

  /// Format plural strings
  String recipesFound(int count) {
    final template = translate(AppStrings.recipesFound);
    return template.replaceAll('{count}', count.toString());
  }

  String photoCount(int count) {
    final isPlural = count != 1;
    final template =
        isPlural ? translate(AppStrings.photos) : translate(AppStrings.photo);
    return '$count $template';
  }

  String hoursAgo(int hours) {
    final template = translate(AppStrings.hoursAgo);
    return template.replaceAll('{hours}', hours.toString());
  }

  String daysAgo(int days) {
    final template = translate(AppStrings.daysAgo);
    return template.replaceAll('{days}', days.toString());
  }

  String weeksAgo(int weeks) {
    final template = translate(AppStrings.weeksAgo);
    return template.replaceAll('{weeks}', weeks.toString());
  }

  // English translations
  static const Map<String, String> _englishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Home',
    AppStrings.navScan: 'Scan',
    AppStrings.navHistory: 'History',
    AppStrings.scanMyFridge: 'Scan my fridge',
    AppStrings.lastResult: 'LAST RESULT',
    AppStrings.recipesFound: '{count} recipes found',
    AppStrings.takePhotosHelper: 'Take 1–3 photos. Messy is okay.',
    AppStrings.uploadFromGallery: 'Upload from gallery',
    AppStrings.reviewPhotos: 'Review Photos',
    AppStrings.tapThumbnailToPreview: 'Tap a thumbnail to preview',
    AppStrings.photo: 'photo',
    AppStrings.photos: 'photos',
    AppStrings.thisIsEnough: 'This is enough',
    AppStrings.addAnotherPhoto: 'Add another photo',
    AppStrings.confirmIngredients: 'Confirm Ingredients',
    AppStrings.heresWhatIThink: "Here's what I think you have.",
    AppStrings.mightBeWrong: 'I might be wrong. Fix anything.',
    AppStrings.addSomethingElse: 'Add something else…',
    AppStrings.cookWithThis: '🍳 Cook with this',
    AppStrings.lookingClosely: 'Looking closely…',
    AppStrings.fridgeHasPotential: 'This fridge has potential.',
    AppStrings.heresWhatYouCanMake: "Here's what you can make",
    AppStrings.editIngredients: 'Edit ingredients',
    AppStrings.scanAgain: 'Scan again',
    AppStrings.recipeBadgeFastLazy: 'Fast & Lazy',
    AppStrings.recipeBadgeActuallyGood: 'Actually Good',
    AppStrings.recipeBadgeShouldntWork: "This Shouldn't Work",
    AppStrings.share: 'Share',
    AppStrings.settings: 'Settings',
    AppStrings.languageLabel: 'Language',
    AppStrings.selectLanguage: 'Select Language',
    AppStrings.clearHistory: 'Clear history',
    AppStrings.historyCleared: 'History cleared',
    AppStrings.about: 'About',
    AppStrings.aboutTitle: 'About FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nA friendly app to help you cook with what you have.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Feedback feature coming soon',
    AppStrings.privacy: 'Privacy',
    AppStrings.privacyTitle: 'Privacy',
    AppStrings.privacyContent:
        'Your photos are processed securely and are not stored permanently.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'History',
    AppStrings.emptyHistory: 'No history yet',
    AppStrings.hoursAgo: '{hours} hours ago',
    AppStrings.yesterday: 'Yesterday',
    AppStrings.daysAgo: '{days} days ago',
    AppStrings.weekAgo: '1 week ago',
    AppStrings.weeksAgo: '{weeks} weeks ago',
  };

  // Spanish translations (example - add more as needed)
  static const Map<String, String> _spanishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Inicio',
    AppStrings.navScan: 'Escanear',
    AppStrings.navHistory: 'Historial',
    AppStrings.scanMyFridge: 'Escanear mi nevera',
    AppStrings.lastResult: 'ÚLTIMO RESULTADO',
    AppStrings.recipesFound: '{count} recetas encontradas',
    AppStrings.takePhotosHelper:
        'Toma 1–3 fotos. Está bien si está desordenado.',
    AppStrings.uploadFromGallery: 'Subir desde galería',
    AppStrings.reviewPhotos: 'Revisar Fotos',
    AppStrings.tapThumbnailToPreview: 'Toca una miniatura para previsualizar',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'fotos',
    AppStrings.thisIsEnough: 'Esto es suficiente',
    AppStrings.addAnotherPhoto: 'Añadir otra foto',
    AppStrings.confirmIngredients: 'Confirmar Ingredientes',
    AppStrings.heresWhatIThink: 'Esto es lo que creo que tienes.',
    AppStrings.mightBeWrong: 'Puedo estar equivocado. Corrige lo que quieras.',
    AppStrings.addSomethingElse: 'Añadir algo más…',
    AppStrings.cookWithThis: '🍳 Cocinar con esto',
    AppStrings.lookingClosely: 'Mirando de cerca…',
    AppStrings.fridgeHasPotential: 'Esta nevera tiene potencial.',
    AppStrings.heresWhatYouCanMake: 'Esto es lo que puedes hacer',
    AppStrings.editIngredients: 'Editar ingredientes',
    AppStrings.scanAgain: 'Escanear de nuevo',
    AppStrings.recipeBadgeFastLazy: 'Rápido y Fácil',
    AppStrings.recipeBadgeActuallyGood: 'Realmente Bueno',
    AppStrings.recipeBadgeShouldntWork: 'Esto No Debería Funcionar',
    AppStrings.share: 'Compartir',
    AppStrings.settings: 'Configuración',
    AppStrings.languageLabel: 'Idioma',
    AppStrings.selectLanguage: 'Seleccionar idioma',
    AppStrings.clearHistory: 'Limpiar historial',
    AppStrings.historyCleared: 'Historial limpiado',
    AppStrings.about: 'Acerca de',
    AppStrings.aboutTitle: 'Acerca de FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nUna aplicación amigable para ayudarte a cocinar con lo que tienes.',
    AppStrings.feedback: 'Comentarios',
    AppStrings.feedbackComingSoon: 'Función de comentarios próximamente',
    AppStrings.privacy: 'Privacidad',
    AppStrings.privacyTitle: 'Privacidad',
    AppStrings.privacyContent:
        'Tus fotos se procesan de forma segura y no se almacenan permanentemente.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historial',
    AppStrings.emptyHistory: 'Aún no hay historial',
    AppStrings.hoursAgo: 'hace {hours} horas',
    AppStrings.yesterday: 'Ayer',
    AppStrings.daysAgo: 'hace {days} días',
    AppStrings.weekAgo: 'hace 1 semana',
    AppStrings.weeksAgo: 'hace {weeks} semanas',
  };

  // Japanese translations
  static const Map<String, String> _japaneseStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'ホーム',
    AppStrings.navScan: 'スキャン',
    AppStrings.navHistory: '履歴',
    AppStrings.scanMyFridge: '冷蔵庫をスキャン',
    AppStrings.lastResult: '最後の結果',
    AppStrings.recipesFound: '{count}個のレシピが見つかりました',
    AppStrings.takePhotosHelper: '1〜3枚の写真を撮ってください。散らかっていても大丈夫です。',
    AppStrings.uploadFromGallery: 'ギャラリーからアップロード',
    AppStrings.reviewPhotos: '写真を確認',
    AppStrings.tapThumbnailToPreview: 'サムネイルをタップしてプレビュー',
    AppStrings.photo: '写真',
    AppStrings.photos: '写真',
    AppStrings.thisIsEnough: 'これで十分です',
    AppStrings.addAnotherPhoto: '別の写真を追加',
    AppStrings.confirmIngredients: '材料を確認',
    AppStrings.heresWhatIThink: 'これがあなたが持っているものだと思います。',
    AppStrings.mightBeWrong: '間違っているかもしれません。何でも修正してください。',
    AppStrings.addSomethingElse: '他に追加…',
    AppStrings.cookWithThis: '🍳 これで料理する',
    AppStrings.lookingClosely: 'よく見ています…',
    AppStrings.fridgeHasPotential: 'この冷蔵庫には可能性があります。',
    AppStrings.heresWhatYouCanMake: 'これが作れるものです',
    AppStrings.editIngredients: '材料を編集',
    AppStrings.scanAgain: 'もう一度スキャン',
    AppStrings.recipeBadgeFastLazy: '簡単＆手軽',
    AppStrings.recipeBadgeActuallyGood: '本当に美味しい',
    AppStrings.recipeBadgeShouldntWork: 'これはうまくいかないはず',
    AppStrings.share: '共有',
    AppStrings.settings: '設定',
    AppStrings.languageLabel: '言語',
    AppStrings.selectLanguage: '言語を選択',
    AppStrings.clearHistory: '履歴をクリア',
    AppStrings.historyCleared: '履歴をクリアしました',
    AppStrings.about: 'について',
    AppStrings.aboutTitle: 'FridgeGPTについて',
    AppStrings.aboutContent: 'FridgeGPT v1\n\n持っているもので料理を手伝う親しみやすいアプリです。',
    AppStrings.feedback: 'フィードバック',
    AppStrings.feedbackComingSoon: 'フィードバック機能は近日公開予定です',
    AppStrings.privacy: 'プライバシー',
    AppStrings.privacyTitle: 'プライバシー',
    AppStrings.privacyContent: 'あなたの写真は安全に処理され、永続的に保存されることはありません。',
    AppStrings.ok: 'OK',
    AppStrings.history: '履歴',
    AppStrings.emptyHistory: 'まだ履歴がありません',
    AppStrings.hoursAgo: '{hours}時間前',
    AppStrings.yesterday: '昨日',
    AppStrings.daysAgo: '{days}日前',
    AppStrings.weekAgo: '1週間前',
    AppStrings.weeksAgo: '{weeks}週間前',
  };

  // French translations
  static const Map<String, String> _frenchStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Accueil',
    AppStrings.navScan: 'Scanner',
    AppStrings.navHistory: 'Historique',
    AppStrings.scanMyFridge: 'Scanner mon frigo',
    AppStrings.lastResult: 'DERNIER RÉSULTAT',
    AppStrings.recipesFound: '{count} recettes trouvées',
    AppStrings.takePhotosHelper: 'Prenez 1 à 3 photos. Le désordre, c\'est OK.',
    AppStrings.uploadFromGallery: 'Télécharger depuis la galerie',
    AppStrings.reviewPhotos: 'Examiner les photos',
    AppStrings.tapThumbnailToPreview:
        'Appuyez sur une miniature pour prévisualiser',
    AppStrings.photo: 'photo',
    AppStrings.photos: 'photos',
    AppStrings.thisIsEnough: 'C\'est suffisant',
    AppStrings.addAnotherPhoto: 'Ajouter une autre photo',
    AppStrings.confirmIngredients: 'Confirmer les ingrédients',
    AppStrings.heresWhatIThink: 'Voici ce que je pense que vous avez.',
    AppStrings.mightBeWrong: 'Je peux me tromper. Corrigez ce que vous voulez.',
    AppStrings.addSomethingElse: 'Ajouter autre chose…',
    AppStrings.cookWithThis: '🍳 Cuisiner avec ça',
    AppStrings.lookingClosely: 'En regardant de près…',
    AppStrings.fridgeHasPotential: 'Ce frigo a du potentiel.',
    AppStrings.heresWhatYouCanMake: 'Voici ce que vous pouvez faire',
    AppStrings.editIngredients: 'Modifier les ingrédients',
    AppStrings.scanAgain: 'Scanner à nouveau',
    AppStrings.recipeBadgeFastLazy: 'Rapide et Facile',
    AppStrings.recipeBadgeActuallyGood: 'Vraiment Bon',
    AppStrings.recipeBadgeShouldntWork: 'Ça ne devrait pas marcher',
    AppStrings.share: 'Partager',
    AppStrings.settings: 'Paramètres',
    AppStrings.languageLabel: 'Langue',
    AppStrings.selectLanguage: 'Sélectionner la langue',
    AppStrings.clearHistory: 'Effacer l\'historique',
    AppStrings.historyCleared: 'Historique effacé',
    AppStrings.about: 'À propos',
    AppStrings.aboutTitle: 'À propos de FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nUne application conviviale pour vous aider à cuisiner avec ce que vous avez.',
    AppStrings.feedback: 'Commentaires',
    AppStrings.feedbackComingSoon: 'Fonctionnalité de commentaires à venir',
    AppStrings.privacy: 'Confidentialité',
    AppStrings.privacyTitle: 'Confidentialité',
    AppStrings.privacyContent:
        'Vos photos sont traitées en toute sécurité et ne sont pas stockées de façon permanente.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historique',
    AppStrings.emptyHistory: 'Aucun historique pour le moment',
    AppStrings.hoursAgo: 'il y a {hours} heures',
    AppStrings.yesterday: 'Hier',
    AppStrings.daysAgo: 'il y a {days} jours',
    AppStrings.weekAgo: 'il y a 1 semaine',
    AppStrings.weeksAgo: 'il y a {weeks} semaines',
  };

  // Chinese (Simplified) translations
  static const Map<String, String> _chineseStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: '首页',
    AppStrings.navScan: '扫描',
    AppStrings.navHistory: '历史',
    AppStrings.scanMyFridge: '扫描我的冰箱',
    AppStrings.lastResult: '最后结果',
    AppStrings.recipesFound: '找到 {count} 个食谱',
    AppStrings.takePhotosHelper: '拍摄 1-3 张照片。凌乱也没关系。',
    AppStrings.uploadFromGallery: '从相册上传',
    AppStrings.reviewPhotos: '查看照片',
    AppStrings.tapThumbnailToPreview: '点击缩略图预览',
    AppStrings.photo: '照片',
    AppStrings.photos: '照片',
    AppStrings.thisIsEnough: '这就够了',
    AppStrings.addAnotherPhoto: '添加另一张照片',
    AppStrings.confirmIngredients: '确认食材',
    AppStrings.heresWhatIThink: '我认为您有这些。',
    AppStrings.mightBeWrong: '我可能错了。请修正任何内容。',
    AppStrings.addSomethingElse: '添加其他东西…',
    AppStrings.cookWithThis: '🍳 用这个烹饪',
    AppStrings.lookingClosely: '仔细查看中…',
    AppStrings.fridgeHasPotential: '这个冰箱有潜力。',
    AppStrings.heresWhatYouCanMake: '这是您可以做的',
    AppStrings.editIngredients: '编辑食材',
    AppStrings.scanAgain: '再次扫描',
    AppStrings.recipeBadgeFastLazy: '快速简单',
    AppStrings.recipeBadgeActuallyGood: '真的不错',
    AppStrings.recipeBadgeShouldntWork: '这不应该行得通',
    AppStrings.share: '分享',
    AppStrings.settings: '设置',
    AppStrings.languageLabel: '语言',
    AppStrings.selectLanguage: '选择语言',
    AppStrings.clearHistory: '清除历史',
    AppStrings.historyCleared: '历史已清除',
    AppStrings.about: '关于',
    AppStrings.aboutTitle: '关于 FridgeGPT',
    AppStrings.aboutContent: 'FridgeGPT v1\n\n一个友好的应用程序，帮助您用现有的食材烹饪。',
    AppStrings.feedback: '反馈',
    AppStrings.feedbackComingSoon: '反馈功能即将推出',
    AppStrings.privacy: '隐私',
    AppStrings.privacyTitle: '隐私',
    AppStrings.privacyContent: '您的照片会被安全处理，不会永久存储。',
    AppStrings.ok: '确定',
    AppStrings.history: '历史',
    AppStrings.emptyHistory: '暂无历史记录',
    AppStrings.hoursAgo: '{hours} 小时前',
    AppStrings.yesterday: '昨天',
    AppStrings.daysAgo: '{days} 天前',
    AppStrings.weekAgo: '1 周前',
    AppStrings.weeksAgo: '{weeks} 周前',
  };

  // German translations
  static const Map<String, String> _germanStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Startseite',
    AppStrings.navScan: 'Scannen',
    AppStrings.navHistory: 'Verlauf',
    AppStrings.scanMyFridge: 'Meinen Kühlschrank scannen',
    AppStrings.lastResult: 'LETZTES ERGEBNIS',
    AppStrings.recipesFound: '{count} Rezepte gefunden',
    AppStrings.takePhotosHelper:
        'Machen Sie 1–3 Fotos. Unordnung ist in Ordnung.',
    AppStrings.uploadFromGallery: 'Aus Galerie hochladen',
    AppStrings.reviewPhotos: 'Fotos überprüfen',
    AppStrings.tapThumbnailToPreview:
        'Tippen Sie auf ein Vorschaubild zur Vorschau',
    AppStrings.photo: 'Foto',
    AppStrings.photos: 'Fotos',
    AppStrings.thisIsEnough: 'Das reicht',
    AppStrings.addAnotherPhoto: 'Weiteres Foto hinzufügen',
    AppStrings.confirmIngredients: 'Zutaten bestätigen',
    AppStrings.heresWhatIThink: 'Das denke ich, was Sie haben.',
    AppStrings.mightBeWrong: 'Ich könnte mich irren. Korrigieren Sie alles.',
    AppStrings.addSomethingElse: 'Etwas anderes hinzufügen…',
    AppStrings.cookWithThis: '🍳 Damit kochen',
    AppStrings.lookingClosely: 'Genau ansehen…',
    AppStrings.fridgeHasPotential: 'Dieser Kühlschrank hat Potenzial.',
    AppStrings.heresWhatYouCanMake: 'Das können Sie machen',
    AppStrings.editIngredients: 'Zutaten bearbeiten',
    AppStrings.scanAgain: 'Erneut scannen',
    AppStrings.recipeBadgeFastLazy: 'Schnell & Einfach',
    AppStrings.recipeBadgeActuallyGood: 'Wirklich Gut',
    AppStrings.recipeBadgeShouldntWork: 'Das sollte nicht funktionieren',
    AppStrings.share: 'Teilen',
    AppStrings.settings: 'Einstellungen',
    AppStrings.languageLabel: 'Sprache',
    AppStrings.selectLanguage: 'Sprache auswählen',
    AppStrings.clearHistory: 'Verlauf löschen',
    AppStrings.historyCleared: 'Verlauf gelöscht',
    AppStrings.about: 'Über',
    AppStrings.aboutTitle: 'Über FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nEine freundliche App, die Ihnen hilft, mit dem zu kochen, was Sie haben.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Feedback-Funktion kommt bald',
    AppStrings.privacy: 'Datenschutz',
    AppStrings.privacyTitle: 'Datenschutz',
    AppStrings.privacyContent:
        'Ihre Fotos werden sicher verarbeitet und nicht dauerhaft gespeichert.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Verlauf',
    AppStrings.emptyHistory: 'Noch kein Verlauf',
    AppStrings.hoursAgo: 'vor {hours} Stunden',
    AppStrings.yesterday: 'Gestern',
    AppStrings.daysAgo: 'vor {days} Tagen',
    AppStrings.weekAgo: 'vor 1 Woche',
    AppStrings.weeksAgo: 'vor {weeks} Wochen',
  };

  // Italian translations
  static const Map<String, String> _italianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Home',
    AppStrings.navScan: 'Scansiona',
    AppStrings.navHistory: 'Cronologia',
    AppStrings.scanMyFridge: 'Scansiona il mio frigo',
    AppStrings.lastResult: 'ULTIMO RISULTATO',
    AppStrings.recipesFound: '{count} ricette trovate',
    AppStrings.takePhotosHelper: 'Scatta 1–3 foto. Va bene se è in disordine.',
    AppStrings.uploadFromGallery: 'Carica dalla galleria',
    AppStrings.reviewPhotos: 'Rivedi le foto',
    AppStrings.tapThumbnailToPreview: 'Tocca una miniatura per l\'anteprima',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'foto',
    AppStrings.thisIsEnough: 'Basta così',
    AppStrings.addAnotherPhoto: 'Aggiungi un\'altra foto',
    AppStrings.confirmIngredients: 'Conferma ingredienti',
    AppStrings.heresWhatIThink: 'Ecco cosa penso tu abbia.',
    AppStrings.mightBeWrong: 'Potrei sbagliarmi. Correggi quello che vuoi.',
    AppStrings.addSomethingElse: 'Aggiungi qualcos\'altro…',
    AppStrings.cookWithThis: '🍳 Cucina con questo',
    AppStrings.lookingClosely: 'Guardando da vicino…',
    AppStrings.fridgeHasPotential: 'Questo frigo ha potenziale.',
    AppStrings.heresWhatYouCanMake: 'Ecco cosa puoi fare',
    AppStrings.editIngredients: 'Modifica ingredienti',
    AppStrings.scanAgain: 'Scansiona di nuovo',
    AppStrings.recipeBadgeFastLazy: 'Veloce e Facile',
    AppStrings.recipeBadgeActuallyGood: 'Davvero Buono',
    AppStrings.recipeBadgeShouldntWork: 'Questo non dovrebbe funzionare',
    AppStrings.share: 'Condividi',
    AppStrings.settings: 'Impostazioni',
    AppStrings.languageLabel: 'Lingua',
    AppStrings.selectLanguage: 'Seleziona lingua',
    AppStrings.clearHistory: 'Cancella cronologia',
    AppStrings.historyCleared: 'Cronologia cancellata',
    AppStrings.about: 'Informazioni',
    AppStrings.aboutTitle: 'Informazioni su FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nUn\'app amichevole per aiutarti a cucinare con quello che hai.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Funzionalità di feedback in arrivo',
    AppStrings.privacy: 'Privacy',
    AppStrings.privacyTitle: 'Privacy',
    AppStrings.privacyContent:
        'Le tue foto vengono elaborate in modo sicuro e non vengono archiviate permanentemente.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Cronologia',
    AppStrings.emptyHistory: 'Nessuna cronologia ancora',
    AppStrings.hoursAgo: '{hours} ore fa',
    AppStrings.yesterday: 'Ieri',
    AppStrings.daysAgo: '{days} giorni fa',
    AppStrings.weekAgo: '1 settimana fa',
    AppStrings.weeksAgo: '{weeks} settimane fa',
  };

  // Korean translations
  static const Map<String, String> _koreanStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: '홈',
    AppStrings.navScan: '스캔',
    AppStrings.navHistory: '기록',
    AppStrings.scanMyFridge: '냉장고 스캔',
    AppStrings.lastResult: '마지막 결과',
    AppStrings.recipesFound: '레시피 {count}개 찾음',
    AppStrings.takePhotosHelper: '사진 1–3장을 찍어주세요. 지저분해도 괜찮습니다.',
    AppStrings.uploadFromGallery: '갤러리에서 업로드',
    AppStrings.reviewPhotos: '사진 검토',
    AppStrings.tapThumbnailToPreview: '썸네일을 탭하여 미리보기',
    AppStrings.photo: '사진',
    AppStrings.photos: '사진',
    AppStrings.thisIsEnough: '이것으로 충분합니다',
    AppStrings.addAnotherPhoto: '다른 사진 추가',
    AppStrings.confirmIngredients: '재료 확인',
    AppStrings.heresWhatIThink: '이것이 가지고 계신 것 같습니다.',
    AppStrings.mightBeWrong: '틀릴 수 있습니다. 수정해주세요.',
    AppStrings.addSomethingElse: '다른 것 추가…',
    AppStrings.cookWithThis: '🍳 이것으로 요리하기',
    AppStrings.lookingClosely: '자세히 살펴보는 중…',
    AppStrings.fridgeHasPotential: '이 냉장고에는 가능성이 있습니다.',
    AppStrings.heresWhatYouCanMake: '만들 수 있는 것들',
    AppStrings.editIngredients: '재료 편집',
    AppStrings.scanAgain: '다시 스캔',
    AppStrings.recipeBadgeFastLazy: '빠르고 간단',
    AppStrings.recipeBadgeActuallyGood: '정말 좋음',
    AppStrings.recipeBadgeShouldntWork: '이건 작동하지 않을 것',
    AppStrings.share: '공유',
    AppStrings.settings: '설정',
    AppStrings.languageLabel: '언어',
    AppStrings.selectLanguage: '언어 선택',
    AppStrings.clearHistory: '기록 지우기',
    AppStrings.historyCleared: '기록이 지워졌습니다',
    AppStrings.about: '정보',
    AppStrings.aboutTitle: 'FridgeGPT 정보',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\n가지고 있는 것으로 요리하는 것을 도와주는 친근한 앱입니다.',
    AppStrings.feedback: '피드백',
    AppStrings.feedbackComingSoon: '피드백 기능 곧 출시',
    AppStrings.privacy: '개인정보 보호',
    AppStrings.privacyTitle: '개인정보 보호',
    AppStrings.privacyContent: '사진은 안전하게 처리되며 영구적으로 저장되지 않습니다.',
    AppStrings.ok: '확인',
    AppStrings.history: '기록',
    AppStrings.emptyHistory: '아직 기록이 없습니다',
    AppStrings.hoursAgo: '{hours}시간 전',
    AppStrings.yesterday: '어제',
    AppStrings.daysAgo: '{days}일 전',
    AppStrings.weekAgo: '1주일 전',
    AppStrings.weeksAgo: '{weeks}주 전',
  };

  // Portuguese translations
  static const Map<String, String> _portugueseStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Início',
    AppStrings.navScan: 'Escanear',
    AppStrings.navHistory: 'Histórico',
    AppStrings.scanMyFridge: 'Escanear minha geladeira',
    AppStrings.lastResult: 'ÚLTIMO RESULTADO',
    AppStrings.recipesFound: '{count} receitas encontradas',
    AppStrings.takePhotosHelper:
        'Tire 1–3 fotos. Está tudo bem se estiver bagunçado.',
    AppStrings.uploadFromGallery: 'Enviar da galeria',
    AppStrings.reviewPhotos: 'Revisar Fotos',
    AppStrings.tapThumbnailToPreview: 'Toque em uma miniatura para visualizar',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'fotos',
    AppStrings.thisIsEnough: 'Isso é suficiente',
    AppStrings.addAnotherPhoto: 'Adicionar outra foto',
    AppStrings.confirmIngredients: 'Confirmar Ingredientes',
    AppStrings.heresWhatIThink: 'Aqui está o que eu acho que você tem.',
    AppStrings.mightBeWrong: 'Posso estar errado. Corrija o que quiser.',
    AppStrings.addSomethingElse: 'Adicionar algo mais…',
    AppStrings.cookWithThis: '🍳 Cozinhar com isso',
    AppStrings.lookingClosely: 'Olhando de perto…',
    AppStrings.fridgeHasPotential: 'Esta geladeira tem potencial.',
    AppStrings.heresWhatYouCanMake: 'Aqui está o que você pode fazer',
    AppStrings.editIngredients: 'Editar ingredientes',
    AppStrings.scanAgain: 'Escanear novamente',
    AppStrings.recipeBadgeFastLazy: 'Rápido e Fácil',
    AppStrings.recipeBadgeActuallyGood: 'Realmente Bom',
    AppStrings.recipeBadgeShouldntWork: 'Isso Não Deveria Funcionar',
    AppStrings.share: 'Compartilhar',
    AppStrings.settings: 'Configurações',
    AppStrings.languageLabel: 'Idioma',
    AppStrings.selectLanguage: 'Selecionar idioma',
    AppStrings.clearHistory: 'Limpar histórico',
    AppStrings.historyCleared: 'Histórico limpo',
    AppStrings.about: 'Sobre',
    AppStrings.aboutTitle: 'Sobre FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nUm aplicativo amigável para ajudá-lo a cozinhar com o que você tem.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Funcionalidade de feedback em breve',
    AppStrings.privacy: 'Privacidade',
    AppStrings.privacyTitle: 'Privacidade',
    AppStrings.privacyContent:
        'Suas fotos são processadas com segurança e não são armazenadas permanentemente.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Histórico',
    AppStrings.emptyHistory: 'Ainda não há histórico',
    AppStrings.hoursAgo: 'há {hours} horas',
    AppStrings.yesterday: 'Ontem',
    AppStrings.daysAgo: 'há {days} dias',
    AppStrings.weekAgo: 'há 1 semana',
    AppStrings.weeksAgo: 'há {weeks} semanas',
  };

  // Russian translations
  static const Map<String, String> _russianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Главная',
    AppStrings.navScan: 'Сканировать',
    AppStrings.navHistory: 'История',
    AppStrings.scanMyFridge: 'Сканировать мой холодильник',
    AppStrings.lastResult: 'ПОСЛЕДНИЙ РЕЗУЛЬТАТ',
    AppStrings.recipesFound: 'Найдено {count} рецептов',
    AppStrings.takePhotosHelper:
        'Сделайте 1–3 фотографии. Беспорядок — это нормально.',
    AppStrings.uploadFromGallery: 'Загрузить из галереи',
    AppStrings.reviewPhotos: 'Просмотр фотографий',
    AppStrings.tapThumbnailToPreview: 'Нажмите на миниатюру для предпросмотра',
    AppStrings.photo: 'фото',
    AppStrings.photos: 'фотографии',
    AppStrings.thisIsEnough: 'Этого достаточно',
    AppStrings.addAnotherPhoto: 'Добавить еще одну фотографию',
    AppStrings.confirmIngredients: 'Подтвердить ингредиенты',
    AppStrings.heresWhatIThink: 'Вот что, я думаю, у вас есть.',
    AppStrings.mightBeWrong: 'Я могу ошибаться. Исправьте что угодно.',
    AppStrings.addSomethingElse: 'Добавить что-то еще…',
    AppStrings.cookWithThis: '🍳 Готовить с этим',
    AppStrings.lookingClosely: 'Присматриваюсь…',
    AppStrings.fridgeHasPotential: 'У этого холодильника есть потенциал.',
    AppStrings.heresWhatYouCanMake: 'Вот что вы можете приготовить',
    AppStrings.editIngredients: 'Редактировать ингредиенты',
    AppStrings.scanAgain: 'Сканировать снова',
    AppStrings.recipeBadgeFastLazy: 'Быстро и Просто',
    AppStrings.recipeBadgeActuallyGood: 'Действительно Хорошо',
    AppStrings.recipeBadgeShouldntWork: 'Это не должно работать',
    AppStrings.share: 'Поделиться',
    AppStrings.settings: 'Настройки',
    AppStrings.languageLabel: 'Язык',
    AppStrings.selectLanguage: 'Выбрать язык',
    AppStrings.clearHistory: 'Очистить историю',
    AppStrings.historyCleared: 'История очищена',
    AppStrings.about: 'О приложении',
    AppStrings.aboutTitle: 'О FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nДружелюбное приложение, которое поможет вам готовить из того, что у вас есть.',
    AppStrings.feedback: 'Обратная связь',
    AppStrings.feedbackComingSoon: 'Функция обратной связи скоро появится',
    AppStrings.privacy: 'Конфиденциальность',
    AppStrings.privacyTitle: 'Конфиденциальность',
    AppStrings.privacyContent:
        'Ваши фотографии обрабатываются безопасно и не хранятся постоянно.',
    AppStrings.ok: 'ОК',
    AppStrings.history: 'История',
    AppStrings.emptyHistory: 'Истории пока нет',
    AppStrings.hoursAgo: '{hours} часов назад',
    AppStrings.yesterday: 'Вчера',
    AppStrings.daysAgo: '{days} дней назад',
    AppStrings.weekAgo: '1 неделю назад',
    AppStrings.weeksAgo: '{weeks} недель назад',
  };

  // Thai translations
  static const Map<String, String> _thaiStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'หน้าแรก',
    AppStrings.navScan: 'สแกน',
    AppStrings.navHistory: 'ประวัติ',
    AppStrings.scanMyFridge: 'สแกนตู้เย็นของฉัน',
    AppStrings.lastResult: 'ผลลัพธ์ล่าสุด',
    AppStrings.recipesFound: 'พบสูตรอาหาร {count} รายการ',
    AppStrings.takePhotosHelper: 'ถ่ายรูป 1–3 张 ไม่เป็นไรถ้าจะยุ่งเหยิง',
    AppStrings.uploadFromGallery: 'อัปโหลดจากแกลเลอรี',
    AppStrings.reviewPhotos: 'ตรวจสอบรูปภาพ',
    AppStrings.tapThumbnailToPreview: 'แตะภาพขนาดย่อเพื่อดูตัวอย่าง',
    AppStrings.photo: 'รูปภาพ',
    AppStrings.photos: 'รูปภาพ',
    AppStrings.thisIsEnough: 'พอแล้ว',
    AppStrings.addAnotherPhoto: 'เพิ่มรูปภาพอีก',
    AppStrings.confirmIngredients: 'ยืนยันส่วนผสม',
    AppStrings.heresWhatIThink: 'นี่คือสิ่งที่ฉันคิดว่าคุณมี',
    AppStrings.mightBeWrong: 'ฉันอาจผิดได้ แก้ไขอะไรก็ได้',
    AppStrings.addSomethingElse: 'เพิ่มอย่างอื่น…',
    AppStrings.cookWithThis: '🍳 ปรุงด้วยสิ่งนี้',
    AppStrings.lookingClosely: 'กำลังดูอย่างใกล้ชิด…',
    AppStrings.fridgeHasPotential: 'ตู้เย็นนี้มีศักยภาพ',
    AppStrings.heresWhatYouCanMake: 'นี่คือสิ่งที่คุณสามารถทำได้',
    AppStrings.editIngredients: 'แก้ไขส่วนผสม',
    AppStrings.scanAgain: 'สแกนอีกครั้ง',
    AppStrings.recipeBadgeFastLazy: 'เร็วและง่าย',
    AppStrings.recipeBadgeActuallyGood: 'ดีจริงๆ',
    AppStrings.recipeBadgeShouldntWork: 'นี่ไม่ควรจะใช้ได้',
    AppStrings.share: 'แชร์',
    AppStrings.settings: 'การตั้งค่า',
    AppStrings.languageLabel: 'ภาษา',
    AppStrings.selectLanguage: 'เลือกภาษา',
    AppStrings.clearHistory: 'ล้างประวัติ',
    AppStrings.historyCleared: 'ล้างประวัติแล้ว',
    AppStrings.about: 'เกี่ยวกับ',
    AppStrings.aboutTitle: 'เกี่ยวกับ FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nแอปที่เป็นมิตรเพื่อช่วยคุณทำอาหารด้วยสิ่งที่คุณมี',
    AppStrings.feedback: 'ความคิดเห็น',
    AppStrings.feedbackComingSoon: 'ฟีเจอร์ความคิดเห็นเร็วๆ นี้',
    AppStrings.privacy: 'ความเป็นส่วนตัว',
    AppStrings.privacyTitle: 'ความเป็นส่วนตัว',
    AppStrings.privacyContent:
        'รูปภาพของคุณจะถูกประมวลผลอย่างปลอดภัยและไม่ถูกเก็บถาวร',
    AppStrings.ok: 'ตกลง',
    AppStrings.history: 'ประวัติ',
    AppStrings.emptyHistory: 'ยังไม่มีประวัติ',
    AppStrings.hoursAgo: '{hours} ชั่วโมงที่แล้ว',
    AppStrings.yesterday: 'เมื่อวาน',
    AppStrings.daysAgo: '{days} วันที่แล้ว',
    AppStrings.weekAgo: '1 สัปดาห์ที่แล้ว',
    AppStrings.weeksAgo: '{weeks} สัปดาห์ที่แล้ว',
  };

  // Dutch translations
  static const Map<String, String> _dutchStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Start',
    AppStrings.navScan: 'Scannen',
    AppStrings.navHistory: 'Geschiedenis',
    AppStrings.scanMyFridge: 'Mijn koelkast scannen',
    AppStrings.lastResult: 'LAATSTE RESULTAAT',
    AppStrings.recipesFound: '{count} recepten gevonden',
    AppStrings.takePhotosHelper: 'Maak 1–3 foto\'s. Rommel is prima.',
    AppStrings.uploadFromGallery: 'Uploaden uit galerij',
    AppStrings.reviewPhotos: 'Foto\'s bekijken',
    AppStrings.tapThumbnailToPreview: 'Tik op een miniatuur om te bekijken',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'foto\'s',
    AppStrings.thisIsEnough: 'Dit is genoeg',
    AppStrings.addAnotherPhoto: 'Nog een foto toevoegen',
    AppStrings.confirmIngredients: 'Ingrediënten bevestigen',
    AppStrings.heresWhatIThink: 'Dit denk ik dat je hebt.',
    AppStrings.mightBeWrong: 'Ik kan het mis hebben. Corrigeer alles.',
    AppStrings.addSomethingElse: 'Iets anders toevoegen…',
    AppStrings.cookWithThis: '🍳 Koken met dit',
    AppStrings.lookingClosely: 'Goed bekijken…',
    AppStrings.fridgeHasPotential: 'Deze koelkast heeft potentieel.',
    AppStrings.heresWhatYouCanMake: 'Dit kun je maken',
    AppStrings.editIngredients: 'Ingrediënten bewerken',
    AppStrings.scanAgain: 'Opnieuw scannen',
    AppStrings.recipeBadgeFastLazy: 'Snel & Gemakkelijk',
    AppStrings.recipeBadgeActuallyGood: 'Echt Goed',
    AppStrings.recipeBadgeShouldntWork: 'Dit Zou Niet Moeten Werken',
    AppStrings.share: 'Delen',
    AppStrings.settings: 'Instellingen',
    AppStrings.languageLabel: 'Taal',
    AppStrings.selectLanguage: 'Taal selecteren',
    AppStrings.clearHistory: 'Geschiedenis wissen',
    AppStrings.historyCleared: 'Geschiedenis gewist',
    AppStrings.about: 'Over',
    AppStrings.aboutTitle: 'Over FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nEen vriendelijke app om je te helpen koken met wat je hebt.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Feedbackfunctie komt binnenkort',
    AppStrings.privacy: 'Privacy',
    AppStrings.privacyTitle: 'Privacy',
    AppStrings.privacyContent:
        'Uw foto\'s worden veilig verwerkt en niet permanent opgeslagen.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Geschiedenis',
    AppStrings.emptyHistory: 'Nog geen geschiedenis',
    AppStrings.hoursAgo: '{hours} uur geleden',
    AppStrings.yesterday: 'Gisteren',
    AppStrings.daysAgo: '{days} dagen geleden',
    AppStrings.weekAgo: '1 week geleden',
    AppStrings.weeksAgo: '{weeks} weken geleden',
  };

  // Polish translations
  static const Map<String, String> _polishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Strona główna',
    AppStrings.navScan: 'Skanuj',
    AppStrings.navHistory: 'Historia',
    AppStrings.scanMyFridge: 'Skanuj moją lodówkę',
    AppStrings.lastResult: 'OSTATNI WYNIK',
    AppStrings.recipesFound: 'Znaleziono {count} przepisów',
    AppStrings.takePhotosHelper: 'Zrób 1–3 zdjęcia. Bałagan jest w porządku.',
    AppStrings.uploadFromGallery: 'Prześlij z galerii',
    AppStrings.reviewPhotos: 'Przejrzyj zdjęcia',
    AppStrings.tapThumbnailToPreview: 'Dotknij miniatury, aby zobaczyć podgląd',
    AppStrings.photo: 'zdjęcie',
    AppStrings.photos: 'zdjęcia',
    AppStrings.thisIsEnough: 'To wystarczy',
    AppStrings.addAnotherPhoto: 'Dodaj kolejne zdjęcie',
    AppStrings.confirmIngredients: 'Potwierdź składniki',
    AppStrings.heresWhatIThink: 'Oto co myślę, że masz.',
    AppStrings.mightBeWrong: 'Mogę się mylić. Popraw cokolwiek.',
    AppStrings.addSomethingElse: 'Dodaj coś innego…',
    AppStrings.cookWithThis: '🍳 Gotuj z tym',
    AppStrings.lookingClosely: 'Przyglądam się uważnie…',
    AppStrings.fridgeHasPotential: 'Ta lodówka ma potencjał.',
    AppStrings.heresWhatYouCanMake: 'Oto co możesz zrobić',
    AppStrings.editIngredients: 'Edytuj składniki',
    AppStrings.scanAgain: 'Skanuj ponownie',
    AppStrings.recipeBadgeFastLazy: 'Szybkie i Proste',
    AppStrings.recipeBadgeActuallyGood: 'Naprawdę Dobre',
    AppStrings.recipeBadgeShouldntWork: 'To Nie Powinno Działać',
    AppStrings.share: 'Udostępnij',
    AppStrings.settings: 'Ustawienia',
    AppStrings.languageLabel: 'Język',
    AppStrings.selectLanguage: 'Wybierz język',
    AppStrings.clearHistory: 'Wyczyść historię',
    AppStrings.historyCleared: 'Historia wyczyszczona',
    AppStrings.about: 'O aplikacji',
    AppStrings.aboutTitle: 'O FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nPrzyjazna aplikacja, która pomoże Ci gotować z tym, co masz.',
    AppStrings.feedback: 'Opinie',
    AppStrings.feedbackComingSoon: 'Funkcja opinii wkrótce',
    AppStrings.privacy: 'Prywatność',
    AppStrings.privacyTitle: 'Prywatność',
    AppStrings.privacyContent:
        'Twoje zdjęcia są bezpiecznie przetwarzane i nie są trwale przechowywane.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historia',
    AppStrings.emptyHistory: 'Brak historii',
    AppStrings.hoursAgo: '{hours} godzin temu',
    AppStrings.yesterday: 'Wczoraj',
    AppStrings.daysAgo: '{days} dni temu',
    AppStrings.weekAgo: '1 tydzień temu',
    AppStrings.weeksAgo: '{weeks} tygodni temu',
  };

  // Turkish translations
  static const Map<String, String> _turkishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Ana Sayfa',
    AppStrings.navScan: 'Tara',
    AppStrings.navHistory: 'Geçmiş',
    AppStrings.scanMyFridge: 'Buzdolabımı tara',
    AppStrings.lastResult: 'SON SONUÇ',
    AppStrings.recipesFound: '{count} tarif bulundu',
    AppStrings.takePhotosHelper: '1–3 fotoğraf çekin. Dağınıklık sorun değil.',
    AppStrings.uploadFromGallery: 'Galeriden yükle',
    AppStrings.reviewPhotos: 'Fotoğrafları İncele',
    AppStrings.tapThumbnailToPreview: 'Önizleme için bir küçük resme dokunun',
    AppStrings.photo: 'fotoğraf',
    AppStrings.photos: 'fotoğraf',
    AppStrings.thisIsEnough: 'Bu yeterli',
    AppStrings.addAnotherPhoto: 'Başka bir fotoğraf ekle',
    AppStrings.confirmIngredients: 'Malzemeleri Onayla',
    AppStrings.heresWhatIThink: 'Bence sahip olduğun şeyler bunlar.',
    AppStrings.mightBeWrong: 'Yanılıyor olabilirim. İstediğin gibi düzelt.',
    AppStrings.addSomethingElse: 'Başka bir şey ekle…',
    AppStrings.cookWithThis: '🍳 Bununla pişir',
    AppStrings.lookingClosely: 'Yakından bakıyorum…',
    AppStrings.fridgeHasPotential: 'Bu buzdolabının potansiyeli var.',
    AppStrings.heresWhatYouCanMake: 'Yapabileceğin şeyler',
    AppStrings.editIngredients: 'Malzemeleri düzenle',
    AppStrings.scanAgain: 'Tekrar tara',
    AppStrings.recipeBadgeFastLazy: 'Hızlı ve Kolay',
    AppStrings.recipeBadgeActuallyGood: 'Gerçekten İyi',
    AppStrings.recipeBadgeShouldntWork: 'Bu Çalışmamalı',
    AppStrings.share: 'Paylaş',
    AppStrings.settings: 'Ayarlar',
    AppStrings.languageLabel: 'Dil',
    AppStrings.selectLanguage: 'Dil seç',
    AppStrings.clearHistory: 'Geçmişi temizle',
    AppStrings.historyCleared: 'Geçmiş temizlendi',
    AppStrings.about: 'Hakkında',
    AppStrings.aboutTitle: 'FridgeGPT Hakkında',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nSahip olduklarınızla yemek yapmanıza yardımcı olan arkadaş canlısı bir uygulama.',
    AppStrings.feedback: 'Geri Bildirim',
    AppStrings.feedbackComingSoon: 'Geri bildirim özelliği yakında',
    AppStrings.privacy: 'Gizlilik',
    AppStrings.privacyTitle: 'Gizlilik',
    AppStrings.privacyContent:
        'Fotoğraflarınız güvenli bir şekilde işlenir ve kalıcı olarak saklanmaz.',
    AppStrings.ok: 'Tamam',
    AppStrings.history: 'Geçmiş',
    AppStrings.emptyHistory: 'Henüz geçmiş yok',
    AppStrings.hoursAgo: '{hours} saat önce',
    AppStrings.yesterday: 'Dün',
    AppStrings.daysAgo: '{days} gün önce',
    AppStrings.weekAgo: '1 hafta önce',
    AppStrings.weeksAgo: '{weeks} hafta önce',
  };

  // Vietnamese translations
  static const Map<String, String> _vietnameseStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Trang chủ',
    AppStrings.navScan: 'Quét',
    AppStrings.navHistory: 'Lịch sử',
    AppStrings.scanMyFridge: 'Quét tủ lạnh của tôi',
    AppStrings.lastResult: 'KẾT QUẢ CUỐI CÙNG',
    AppStrings.recipesFound: 'Tìm thấy {count} công thức',
    AppStrings.takePhotosHelper: 'Chụp 1–3 ảnh. Lộn xộn cũng không sao.',
    AppStrings.uploadFromGallery: 'Tải lên từ thư viện',
    AppStrings.reviewPhotos: 'Xem lại ảnh',
    AppStrings.tapThumbnailToPreview: 'Chạm vào hình thu nhỏ để xem trước',
    AppStrings.photo: 'ảnh',
    AppStrings.photos: 'ảnh',
    AppStrings.thisIsEnough: 'Đủ rồi',
    AppStrings.addAnotherPhoto: 'Thêm ảnh khác',
    AppStrings.confirmIngredients: 'Xác nhận nguyên liệu',
    AppStrings.heresWhatIThink: 'Đây là những gì tôi nghĩ bạn có.',
    AppStrings.mightBeWrong: 'Tôi có thể sai. Sửa bất cứ thứ gì.',
    AppStrings.addSomethingElse: 'Thêm thứ khác…',
    AppStrings.cookWithThis: '🍳 Nấu với cái này',
    AppStrings.lookingClosely: 'Đang xem kỹ…',
    AppStrings.fridgeHasPotential: 'Tủ lạnh này có tiềm năng.',
    AppStrings.heresWhatYouCanMake: 'Đây là những gì bạn có thể làm',
    AppStrings.editIngredients: 'Chỉnh sửa nguyên liệu',
    AppStrings.scanAgain: 'Quét lại',
    AppStrings.recipeBadgeFastLazy: 'Nhanh và Dễ',
    AppStrings.recipeBadgeActuallyGood: 'Thực Sự Tốt',
    AppStrings.recipeBadgeShouldntWork: 'Điều Này Không Nên Hoạt Động',
    AppStrings.share: 'Chia sẻ',
    AppStrings.settings: 'Cài đặt',
    AppStrings.languageLabel: 'Ngôn ngữ',
    AppStrings.selectLanguage: 'Chọn ngôn ngữ',
    AppStrings.clearHistory: 'Xóa lịch sử',
    AppStrings.historyCleared: 'Đã xóa lịch sử',
    AppStrings.about: 'Giới thiệu',
    AppStrings.aboutTitle: 'Giới thiệu FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nỨng dụng thân thiện giúp bạn nấu ăn với những gì bạn có.',
    AppStrings.feedback: 'Phản hồi',
    AppStrings.feedbackComingSoon: 'Tính năng phản hồi sắp ra mắt',
    AppStrings.privacy: 'Quyền riêng tư',
    AppStrings.privacyTitle: 'Quyền riêng tư',
    AppStrings.privacyContent:
        'Ảnh của bạn được xử lý an toàn và không được lưu trữ vĩnh viễn.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Lịch sử',
    AppStrings.emptyHistory: 'Chưa có lịch sử',
    AppStrings.hoursAgo: '{hours} giờ trước',
    AppStrings.yesterday: 'Hôm qua',
    AppStrings.daysAgo: '{days} ngày trước',
    AppStrings.weekAgo: '1 tuần trước',
    AppStrings.weeksAgo: '{weeks} tuần trước',
  };

  // Arabic translations
  static const Map<String, String> _arabicStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'الرئيسية',
    AppStrings.navScan: 'مسح',
    AppStrings.navHistory: 'السجل',
    AppStrings.scanMyFridge: 'مسح ثلاجتي',
    AppStrings.lastResult: 'النتيجة الأخيرة',
    AppStrings.recipesFound: 'تم العثور على {count} وصفة',
    AppStrings.takePhotosHelper: 'التقط 1-3 صور. لا بأس إذا كانت فوضوية.',
    AppStrings.uploadFromGallery: 'رفع من المعرض',
    AppStrings.reviewPhotos: 'مراجعة الصور',
    AppStrings.tapThumbnailToPreview: 'اضغط على الصورة المصغرة للمعاينة',
    AppStrings.photo: 'صورة',
    AppStrings.photos: 'صور',
    AppStrings.thisIsEnough: 'هذا كافٍ',
    AppStrings.addAnotherPhoto: 'إضافة صورة أخرى',
    AppStrings.confirmIngredients: 'تأكيد المكونات',
    AppStrings.heresWhatIThink: 'هذا ما أعتقد أن لديك.',
    AppStrings.mightBeWrong: 'قد أكون مخطئاً. صحح أي شيء.',
    AppStrings.addSomethingElse: 'أضف شيئاً آخر…',
    AppStrings.cookWithThis: '🍳 اطبخ بهذا',
    AppStrings.lookingClosely: 'أبحث بعناية…',
    AppStrings.fridgeHasPotential: 'هذه الثلاجة لديها إمكانات.',
    AppStrings.heresWhatYouCanMake: 'هذا ما يمكنك صنعه',
    AppStrings.editIngredients: 'تحرير المكونات',
    AppStrings.scanAgain: 'مسح مرة أخرى',
    AppStrings.recipeBadgeFastLazy: 'سريع وسهل',
    AppStrings.recipeBadgeActuallyGood: 'جيد حقاً',
    AppStrings.recipeBadgeShouldntWork: 'هذا لا ينبغي أن يعمل',
    AppStrings.share: 'مشاركة',
    AppStrings.settings: 'الإعدادات',
    AppStrings.languageLabel: 'اللغة',
    AppStrings.selectLanguage: 'اختر اللغة',
    AppStrings.clearHistory: 'مسح السجل',
    AppStrings.historyCleared: 'تم مسح السجل',
    AppStrings.about: 'حول',
    AppStrings.aboutTitle: 'حول FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nتطبيق ودود لمساعدتك على الطهي بما لديك.',
    AppStrings.feedback: 'تعليقات',
    AppStrings.feedbackComingSoon: 'ميزة التعليقات قريباً',
    AppStrings.privacy: 'الخصوصية',
    AppStrings.privacyTitle: 'الخصوصية',
    AppStrings.privacyContent:
        'يتم معالجة صورك بأمان ولا يتم تخزينها بشكل دائم.',
    AppStrings.ok: 'موافق',
    AppStrings.history: 'السجل',
    AppStrings.emptyHistory: 'لا يوجد تاريخ بعد',
    AppStrings.hoursAgo: 'منذ {hours} ساعة',
    AppStrings.yesterday: 'أمس',
    AppStrings.daysAgo: 'منذ {days} يوم',
    AppStrings.weekAgo: 'منذ أسبوع واحد',
    AppStrings.weeksAgo: 'منذ {weeks} أسبوع',
  };

  // Hindi translations
  static const Map<String, String> _hindiStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'होम',
    AppStrings.navScan: 'स्कैन करें',
    AppStrings.navHistory: 'इतिहास',
    AppStrings.scanMyFridge: 'मेरे फ्रिज को स्कैन करें',
    AppStrings.lastResult: 'अंतिम परिणाम',
    AppStrings.recipesFound: '{count} रेसिपी मिलीं',
    AppStrings.takePhotosHelper: '1-3 तस्वीरें लें। गड़बड़ होना ठीक है।',
    AppStrings.uploadFromGallery: 'गैलरी से अपलोड करें',
    AppStrings.reviewPhotos: 'तस्वीरें देखें',
    AppStrings.tapThumbnailToPreview: 'पूर्वावलोकन के लिए थंबनेल पर टैप करें',
    AppStrings.photo: 'तस्वीर',
    AppStrings.photos: 'तस्वीरें',
    AppStrings.thisIsEnough: 'यह काफी है',
    AppStrings.addAnotherPhoto: 'एक और तस्वीर जोड़ें',
    AppStrings.confirmIngredients: 'सामग्री की पुष्टि करें',
    AppStrings.heresWhatIThink: 'मुझे लगता है कि आपके पास ये हैं।',
    AppStrings.mightBeWrong: 'मैं गलत हो सकता हूं। कुछ भी सुधारें।',
    AppStrings.addSomethingElse: 'कुछ और जोड़ें…',
    AppStrings.cookWithThis: '🍳 इससे पकाएं',
    AppStrings.lookingClosely: 'बारीकी से देख रहा हूं…',
    AppStrings.fridgeHasPotential: 'इस फ्रिज में संभावना है।',
    AppStrings.heresWhatYouCanMake: 'यह आप बना सकते हैं',
    AppStrings.editIngredients: 'सामग्री संपादित करें',
    AppStrings.scanAgain: 'फिर से स्कैन करें',
    AppStrings.recipeBadgeFastLazy: 'तेज़ और आसान',
    AppStrings.recipeBadgeActuallyGood: 'वास्तव में अच्छा',
    AppStrings.recipeBadgeShouldntWork: 'यह काम नहीं करना चाहिए',
    AppStrings.share: 'साझा करें',
    AppStrings.settings: 'सेटिंग्स',
    AppStrings.languageLabel: 'भाषा',
    AppStrings.selectLanguage: 'भाषा चुनें',
    AppStrings.clearHistory: 'इतिहास साफ करें',
    AppStrings.historyCleared: 'इतिहास साफ हो गया',
    AppStrings.about: 'के बारे में',
    AppStrings.aboutTitle: 'FridgeGPT के बारे में',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nआपके पास जो है उससे खाना बनाने में मदद करने के लिए एक अनुकूल ऐप।',
    AppStrings.feedback: 'प्रतिक्रिया',
    AppStrings.feedbackComingSoon: 'प्रतिक्रिया सुविधा जल्द ही आ रही है',
    AppStrings.privacy: 'गोपनीयता',
    AppStrings.privacyTitle: 'गोपनीयता',
    AppStrings.privacyContent:
        'आपकी तस्वीरें सुरक्षित रूप से संसाधित की जाती हैं और स्थायी रूप से संग्रहीत नहीं की जाती हैं।',
    AppStrings.ok: 'ठीक है',
    AppStrings.history: 'इतिहास',
    AppStrings.emptyHistory: 'अभी तक कोई इतिहास नहीं',
    AppStrings.hoursAgo: '{hours} घंटे पहले',
    AppStrings.yesterday: 'कल',
    AppStrings.daysAgo: '{days} दिन पहले',
    AppStrings.weekAgo: '1 सप्ताह पहले',
    AppStrings.weeksAgo: '{weeks} सप्ताह पहले',
  };

  // Indonesian translations
  static const Map<String, String> _indonesianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Beranda',
    AppStrings.navScan: 'Pindai',
    AppStrings.navHistory: 'Riwayat',
    AppStrings.scanMyFridge: 'Pindai kulkas saya',
    AppStrings.lastResult: 'HASIL TERAKHIR',
    AppStrings.recipesFound: '{count} resep ditemukan',
    AppStrings.takePhotosHelper: 'Ambil 1–3 foto. Berantakan tidak apa-apa.',
    AppStrings.uploadFromGallery: 'Unggah dari galeri',
    AppStrings.reviewPhotos: 'Tinjau Foto',
    AppStrings.tapThumbnailToPreview: 'Ketuk thumbnail untuk pratinjau',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'foto',
    AppStrings.thisIsEnough: 'Ini sudah cukup',
    AppStrings.addAnotherPhoto: 'Tambahkan foto lain',
    AppStrings.confirmIngredients: 'Konfirmasi Bahan',
    AppStrings.heresWhatIThink: 'Ini yang saya pikir Anda miliki.',
    AppStrings.mightBeWrong: 'Saya mungkin salah. Perbaiki apa saja.',
    AppStrings.addSomethingElse: 'Tambahkan sesuatu yang lain…',
    AppStrings.cookWithThis: '🍳 Masak dengan ini',
    AppStrings.lookingClosely: 'Melihat dengan teliti…',
    AppStrings.fridgeHasPotential: 'Kulkas ini memiliki potensi.',
    AppStrings.heresWhatYouCanMake: 'Ini yang bisa Anda buat',
    AppStrings.editIngredients: 'Edit bahan',
    AppStrings.scanAgain: 'Pindai lagi',
    AppStrings.recipeBadgeFastLazy: 'Cepat & Mudah',
    AppStrings.recipeBadgeActuallyGood: 'Benar-benar Enak',
    AppStrings.recipeBadgeShouldntWork: 'Ini Seharusnya Tidak Berfungsi',
    AppStrings.share: 'Bagikan',
    AppStrings.settings: 'Pengaturan',
    AppStrings.languageLabel: 'Bahasa',
    AppStrings.selectLanguage: 'Pilih Bahasa',
    AppStrings.clearHistory: 'Hapus riwayat',
    AppStrings.historyCleared: 'Riwayat dihapus',
    AppStrings.about: 'Tentang',
    AppStrings.aboutTitle: 'Tentang FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nAplikasi ramah untuk membantu Anda memasak dengan apa yang Anda miliki.',
    AppStrings.feedback: 'Masukan',
    AppStrings.feedbackComingSoon: 'Fitur masukan segera hadir',
    AppStrings.privacy: 'Privasi',
    AppStrings.privacyTitle: 'Privasi',
    AppStrings.privacyContent:
        'Foto Anda diproses dengan aman dan tidak disimpan secara permanen.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Riwayat',
    AppStrings.emptyHistory: 'Belum ada riwayat',
    AppStrings.hoursAgo: '{hours} jam yang lalu',
    AppStrings.yesterday: 'Kemarin',
    AppStrings.daysAgo: '{days} hari yang lalu',
    AppStrings.weekAgo: '1 minggu yang lalu',
    AppStrings.weeksAgo: '{weeks} minggu yang lalu',
  };

  // Bengali translations
  static const Map<String, String> _bengaliStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'হোম',
    AppStrings.navScan: 'স্ক্যান',
    AppStrings.navHistory: 'ইতিহাস',
    AppStrings.scanMyFridge: 'আমার ফ্রিজ স্ক্যান করুন',
    AppStrings.lastResult: 'শেষ ফলাফল',
    AppStrings.recipesFound: '{count}টি রেসিপি পাওয়া গেছে',
    AppStrings.takePhotosHelper: '1-3টি ছবি তুলুন। এলোমেলো হলেও সমস্যা নেই।',
    AppStrings.uploadFromGallery: 'গ্যালারি থেকে আপলোড করুন',
    AppStrings.reviewPhotos: 'ছবি পর্যালোচনা করুন',
    AppStrings.tapThumbnailToPreview: 'প্রিভিউ করতে থাম্বনেইলে ট্যাপ করুন',
    AppStrings.photo: 'ছবি',
    AppStrings.photos: 'ছবি',
    AppStrings.thisIsEnough: 'এটাই যথেষ্ট',
    AppStrings.addAnotherPhoto: 'আরেকটি ছবি যোগ করুন',
    AppStrings.confirmIngredients: 'উপাদান নিশ্চিত করুন',
    AppStrings.heresWhatIThink: 'আমার মনে হয় আপনার কাছে এগুলো আছে।',
    AppStrings.mightBeWrong: 'আমি ভুল হতে পারি। যেকোনো কিছু ঠিক করুন।',
    AppStrings.addSomethingElse: 'অন্য কিছু যোগ করুন…',
    AppStrings.cookWithThis: '🍳 এটি দিয়ে রান্না করুন',
    AppStrings.lookingClosely: 'কাছ থেকে দেখছি…',
    AppStrings.fridgeHasPotential: 'এই ফ্রিজের সম্ভাবনা আছে।',
    AppStrings.heresWhatYouCanMake: 'আপনি এটি তৈরি করতে পারেন',
    AppStrings.editIngredients: 'উপাদান সম্পাদনা করুন',
    AppStrings.scanAgain: 'আবার স্ক্যান করুন',
    AppStrings.recipeBadgeFastLazy: 'দ্রুত এবং সহজ',
    AppStrings.recipeBadgeActuallyGood: 'সত্যিই ভালো',
    AppStrings.recipeBadgeShouldntWork: 'এটি কাজ করা উচিত নয়',
    AppStrings.share: 'শেয়ার করুন',
    AppStrings.settings: 'সেটিংস',
    AppStrings.languageLabel: 'ভাষা',
    AppStrings.selectLanguage: 'ভাষা নির্বাচন করুন',
    AppStrings.clearHistory: 'ইতিহাস সাফ করুন',
    AppStrings.historyCleared: 'ইতিহাস সাফ করা হয়েছে',
    AppStrings.about: 'সম্পর্কে',
    AppStrings.aboutTitle: 'FridgeGPT সম্পর্কে',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nআপনার যা আছে তা দিয়ে রান্না করতে সাহায্য করার জন্য একটি বন্ধুত্বপূর্ণ অ্যাপ।',
    AppStrings.feedback: 'মতামত',
    AppStrings.feedbackComingSoon: 'মতামত বৈশিষ্ট্য শীঘ্রই আসছে',
    AppStrings.privacy: 'গোপনীয়তা',
    AppStrings.privacyTitle: 'গোপনীয়তা',
    AppStrings.privacyContent:
        'আপনার ছবিগুলি নিরাপদে প্রক্রিয়া করা হয় এবং স্থায়ীভাবে সংরক্ষণ করা হয় না।',
    AppStrings.ok: 'ঠিক আছে',
    AppStrings.history: 'ইতিহাস',
    AppStrings.emptyHistory: 'এখনও কোন ইতিহাস নেই',
    AppStrings.hoursAgo: '{hours} ঘন্টা আগে',
    AppStrings.yesterday: 'গতকাল',
    AppStrings.daysAgo: '{days} দিন আগে',
    AppStrings.weekAgo: '1 সপ্তাহ আগে',
    AppStrings.weeksAgo: '{weeks} সপ্তাহ আগে',
  };

  // Danish translations
  static const Map<String, String> _danishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Hjem',
    AppStrings.navScan: 'Scan',
    AppStrings.navHistory: 'Historik',
    AppStrings.scanMyFridge: 'Scan min køleskab',
    AppStrings.lastResult: 'SIDSTE RESULTAT',
    AppStrings.recipesFound: '{count} opskrifter fundet',
    AppStrings.takePhotosHelper: 'Tag 1–3 billeder. Rod er okay.',
    AppStrings.uploadFromGallery: 'Upload fra galleri',
    AppStrings.reviewPhotos: 'Gennemgå billeder',
    AppStrings.tapThumbnailToPreview:
        'Tryk på et miniaturebillede for at forhåndsvise',
    AppStrings.photo: 'billede',
    AppStrings.photos: 'billeder',
    AppStrings.thisIsEnough: 'Dette er nok',
    AppStrings.addAnotherPhoto: 'Tilføj et andet billede',
    AppStrings.confirmIngredients: 'Bekræft ingredienser',
    AppStrings.heresWhatIThink: 'Her er hvad jeg tror du har.',
    AppStrings.mightBeWrong: 'Jeg kan tage fejl. Ret hvad som helst.',
    AppStrings.addSomethingElse: 'Tilføj noget andet…',
    AppStrings.cookWithThis: '🍳 Lav mad med dette',
    AppStrings.lookingClosely: 'Ser nøje efter…',
    AppStrings.fridgeHasPotential: 'Dette køleskab har potentiale.',
    AppStrings.heresWhatYouCanMake: 'Her er hvad du kan lave',
    AppStrings.editIngredients: 'Rediger ingredienser',
    AppStrings.scanAgain: 'Scan igen',
    AppStrings.recipeBadgeFastLazy: 'Hurtig og Nem',
    AppStrings.recipeBadgeActuallyGood: 'Virkelig God',
    AppStrings.recipeBadgeShouldntWork: 'Dette Burde Ikke Virke',
    AppStrings.share: 'Del',
    AppStrings.settings: 'Indstillinger',
    AppStrings.languageLabel: 'Sprog',
    AppStrings.selectLanguage: 'Vælg sprog',
    AppStrings.clearHistory: 'Ryd historik',
    AppStrings.historyCleared: 'Historik ryddet',
    AppStrings.about: 'Om',
    AppStrings.aboutTitle: 'Om FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nEn venlig app til at hjælpe dig med at lave mad med det, du har.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Feedback-funktion kommer snart',
    AppStrings.privacy: 'Fortrolighed',
    AppStrings.privacyTitle: 'Fortrolighed',
    AppStrings.privacyContent:
        'Dine billeder behandles sikkert og gemmes ikke permanent.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historik',
    AppStrings.emptyHistory: 'Ingen historik endnu',
    AppStrings.hoursAgo: 'for {hours} timer siden',
    AppStrings.yesterday: 'I går',
    AppStrings.daysAgo: 'for {days} dage siden',
    AppStrings.weekAgo: 'for 1 uge siden',
    AppStrings.weeksAgo: 'for {weeks} uger siden',
  };

  // Finnish translations
  static const Map<String, String> _finnishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Koti',
    AppStrings.navScan: 'Skannaa',
    AppStrings.navHistory: 'Historia',
    AppStrings.scanMyFridge: 'Skannaa jääkaappini',
    AppStrings.lastResult: 'VIIMEINEN TULOS',
    AppStrings.recipesFound: '{count} reseptiä löytyi',
    AppStrings.takePhotosHelper: 'Ota 1–3 kuvaa. Sotkuinen on ok.',
    AppStrings.uploadFromGallery: 'Lataa galleriasta',
    AppStrings.reviewPhotos: 'Tarkista kuvat',
    AppStrings.tapThumbnailToPreview: 'Napauta pikkukuvaa esikatsellaksesi',
    AppStrings.photo: 'kuva',
    AppStrings.photos: 'kuvat',
    AppStrings.thisIsEnough: 'Tämä riittää',
    AppStrings.addAnotherPhoto: 'Lisää toinen kuva',
    AppStrings.confirmIngredients: 'Vahvista ainekset',
    AppStrings.heresWhatIThink: 'Tässä on mitä luulen sinulla olevan.',
    AppStrings.mightBeWrong: 'Voin olla väärässä. Korjaa mitä tahansa.',
    AppStrings.addSomethingElse: 'Lisää jotain muuta…',
    AppStrings.cookWithThis: '🍳 Keitä tällä',
    AppStrings.lookingClosely: 'Katselen tarkasti…',
    AppStrings.fridgeHasPotential: 'Tällä jääkaapilla on potentiaalia.',
    AppStrings.heresWhatYouCanMake: 'Tässä on mitä voit tehdä',
    AppStrings.editIngredients: 'Muokkaa aineksia',
    AppStrings.scanAgain: 'Skannaa uudelleen',
    AppStrings.recipeBadgeFastLazy: 'Nopea ja Helppo',
    AppStrings.recipeBadgeActuallyGood: 'Todella Hyvä',
    AppStrings.recipeBadgeShouldntWork: 'Tämän Ei Pitäisi Toimia',
    AppStrings.share: 'Jaa',
    AppStrings.settings: 'Asetukset',
    AppStrings.languageLabel: 'Kieli',
    AppStrings.selectLanguage: 'Valitse kieli',
    AppStrings.clearHistory: 'Tyhjennä historia',
    AppStrings.historyCleared: 'Historia tyhjennetty',
    AppStrings.about: 'Tietoja',
    AppStrings.aboutTitle: 'Tietoja FridgeGPT:stä',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nYstävällinen sovellus, joka auttaa sinua keittämään sillä, mitä sinulla on.',
    AppStrings.feedback: 'Palaute',
    AppStrings.feedbackComingSoon: 'Palautetoiminto tulossa pian',
    AppStrings.privacy: 'Yksityisyys',
    AppStrings.privacyTitle: 'Yksityisyys',
    AppStrings.privacyContent:
        'Kuvasi käsitellään turvallisesti eikä niitä tallenneta pysyvästi.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historia',
    AppStrings.emptyHistory: 'Ei vielä historiaa',
    AppStrings.hoursAgo: '{hours} tuntia sitten',
    AppStrings.yesterday: 'Eilen',
    AppStrings.daysAgo: '{days} päivää sitten',
    AppStrings.weekAgo: '1 viikko sitten',
    AppStrings.weeksAgo: '{weeks} viikkoa sitten',
  };

  // Greek translations
  static const Map<String, String> _greekStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Αρχική',
    AppStrings.navScan: 'Σάρωση',
    AppStrings.navHistory: 'Ιστορικό',
    AppStrings.scanMyFridge: 'Σάρωση ψυγείου',
    AppStrings.lastResult: 'ΤΕΛΕΥΤΑΙΟ ΑΠΟΤΕΛΕΣΜΑ',
    AppStrings.recipesFound: 'Βρέθηκαν {count} συνταγές',
    AppStrings.takePhotosHelper:
        'Τραβήξτε 1–3 φωτογραφίες. Το χάος είναι εντάξει.',
    AppStrings.uploadFromGallery: 'Ανέβασμα από τη συλλογή',
    AppStrings.reviewPhotos: 'Επανεξέταση Φωτογραφιών',
    AppStrings.tapThumbnailToPreview:
        'Πατήστε μια μικρογραφία για προεπισκόπηση',
    AppStrings.photo: 'φωτογραφία',
    AppStrings.photos: 'φωτογραφίες',
    AppStrings.thisIsEnough: 'Αυτό είναι αρκετό',
    AppStrings.addAnotherPhoto: 'Προσθήκη άλλης φωτογραφίας',
    AppStrings.confirmIngredients: 'Επιβεβαίωση Υλικών',
    AppStrings.heresWhatIThink: 'Αυτά νομίζω ότι έχετε.',
    AppStrings.mightBeWrong: 'Μπορεί να κάνω λάθος. Διορθώστε οτιδήποτε.',
    AppStrings.addSomethingElse: 'Προσθέστε κάτι άλλο…',
    AppStrings.cookWithThis: '🍳 Μαγειρέψτε με αυτό',
    AppStrings.lookingClosely: 'Κοιτάζω προσεκτικά…',
    AppStrings.fridgeHasPotential: 'Αυτό το ψυγείο έχει δυνατότητες.',
    AppStrings.heresWhatYouCanMake: 'Αυτά μπορείτε να φτιάξετε',
    AppStrings.editIngredients: 'Επεξεργασία υλικών',
    AppStrings.scanAgain: 'Σάρωση ξανά',
    AppStrings.recipeBadgeFastLazy: 'Γρήγορο & Εύκολο',
    AppStrings.recipeBadgeActuallyGood: 'Πραγματικά Καλό',
    AppStrings.recipeBadgeShouldntWork: 'Αυτό Δεν Θα Έπρεπε Να Λειτουργεί',
    AppStrings.share: 'Κοινοποίηση',
    AppStrings.settings: 'Ρυθμίσεις',
    AppStrings.languageLabel: 'Γλώσσα',
    AppStrings.selectLanguage: 'Επιλογή γλώσσας',
    AppStrings.clearHistory: 'Εκκαθάριση ιστορικού',
    AppStrings.historyCleared: 'Το ιστορικό εκκαθαρίστηκε',
    AppStrings.about: 'Σχετικά',
    AppStrings.aboutTitle: 'Σχετικά με το FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nΜια φιλική εφαρμογή για να σας βοηθήσει να μαγειρέψετε με ό,τι έχετε.',
    AppStrings.feedback: 'Σχόλια',
    AppStrings.feedbackComingSoon: 'Η λειτουργία σχολίων έρχεται σύντομα',
    AppStrings.privacy: 'Απόρρητο',
    AppStrings.privacyTitle: 'Απόρρητο',
    AppStrings.privacyContent:
        'Οι φωτογραφίες σας επεξεργάζονται με ασφάλεια και δεν αποθηκεύονται μόνιμα.',
    AppStrings.ok: 'Εντάξει',
    AppStrings.history: 'Ιστορικό',
    AppStrings.emptyHistory: 'Δεν υπάρχει ιστορικό ακόμα',
    AppStrings.hoursAgo: 'πριν {hours} ώρες',
    AppStrings.yesterday: 'Χθες',
    AppStrings.daysAgo: 'πριν {days} ημέρες',
    AppStrings.weekAgo: 'πριν 1 εβδομάδα',
    AppStrings.weeksAgo: 'πριν {weeks} εβδομάδες',
  };

  // Hebrew translations
  static const Map<String, String> _hebrewStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'בית',
    AppStrings.navScan: 'סרוק',
    AppStrings.navHistory: 'היסטוריה',
    AppStrings.scanMyFridge: 'סרוק את המקרר שלי',
    AppStrings.lastResult: 'תוצאה אחרונה',
    AppStrings.recipesFound: 'נמצאו {count} מתכונים',
    AppStrings.takePhotosHelper: 'צלם 1–3 תמונות. בלגן זה בסדר.',
    AppStrings.uploadFromGallery: 'העלה מהגלריה',
    AppStrings.reviewPhotos: 'סקור תמונות',
    AppStrings.tapThumbnailToPreview: 'הקש על תמונה ממוזערת לתצוגה מקדימה',
    AppStrings.photo: 'תמונה',
    AppStrings.photos: 'תמונות',
    AppStrings.thisIsEnough: 'זה מספיק',
    AppStrings.addAnotherPhoto: 'הוסף תמונה נוספת',
    AppStrings.confirmIngredients: 'אשר מרכיבים',
    AppStrings.heresWhatIThink: 'הנה מה שאני חושב שיש לך.',
    AppStrings.mightBeWrong: 'אני עלול לטעות. תקן כל דבר.',
    AppStrings.addSomethingElse: 'הוסף משהו אחר…',
    AppStrings.cookWithThis: '🍳 בישל עם זה',
    AppStrings.lookingClosely: 'מסתכל מקרוב…',
    AppStrings.fridgeHasPotential: 'למקרר הזה יש פוטנציאל.',
    AppStrings.heresWhatYouCanMake: 'הנה מה שאתה יכול להכין',
    AppStrings.editIngredients: 'ערוך מרכיבים',
    AppStrings.scanAgain: 'סרוק שוב',
    AppStrings.recipeBadgeFastLazy: 'מהיר וקל',
    AppStrings.recipeBadgeActuallyGood: 'באמת טוב',
    AppStrings.recipeBadgeShouldntWork: 'זה לא אמור לעבוד',
    AppStrings.share: 'שתף',
    AppStrings.settings: 'הגדרות',
    AppStrings.languageLabel: 'שפה',
    AppStrings.selectLanguage: 'בחר שפה',
    AppStrings.clearHistory: 'נקה היסטוריה',
    AppStrings.historyCleared: 'ההיסטוריה נוקתה',
    AppStrings.about: 'אודות',
    AppStrings.aboutTitle: 'אודות FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nאפליקציה ידידותית שתעזור לך לבשל עם מה שיש לך.',
    AppStrings.feedback: 'משוב',
    AppStrings.feedbackComingSoon: 'תכונת המשוב תגיע בקרוב',
    AppStrings.privacy: 'פרטיות',
    AppStrings.privacyTitle: 'פרטיות',
    AppStrings.privacyContent:
        'התמונות שלך מעובדות בצורה מאובטחת ולא נשמרות לצמיתות.',
    AppStrings.ok: 'אישור',
    AppStrings.history: 'היסטוריה',
    AppStrings.emptyHistory: 'אין היסטוריה עדיין',
    AppStrings.hoursAgo: 'לפני {hours} שעות',
    AppStrings.yesterday: 'אתמול',
    AppStrings.daysAgo: 'לפני {days} ימים',
    AppStrings.weekAgo: 'לפני שבוע אחד',
    AppStrings.weeksAgo: 'לפני {weeks} שבועות',
  };

  // Norwegian translations
  static const Map<String, String> _norwegianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Hjem',
    AppStrings.navScan: 'Skann',
    AppStrings.navHistory: 'Historikk',
    AppStrings.scanMyFridge: 'Skann kjøleskapet mitt',
    AppStrings.lastResult: 'SISTE RESULTAT',
    AppStrings.recipesFound: '{count} oppskrifter funnet',
    AppStrings.takePhotosHelper: 'Ta 1–3 bilder. Rot er greit.',
    AppStrings.uploadFromGallery: 'Last opp fra galleri',
    AppStrings.reviewPhotos: 'Gjennomgå bilder',
    AppStrings.tapThumbnailToPreview:
        'Trykk på et miniatyrbilde for å forhåndsvise',
    AppStrings.photo: 'bilde',
    AppStrings.photos: 'bilder',
    AppStrings.thisIsEnough: 'Dette er nok',
    AppStrings.addAnotherPhoto: 'Legg til et annet bilde',
    AppStrings.confirmIngredients: 'Bekreft ingredienser',
    AppStrings.heresWhatIThink: 'Her er hva jeg tror du har.',
    AppStrings.mightBeWrong: 'Jeg kan ta feil. Rett hva som helst.',
    AppStrings.addSomethingElse: 'Legg til noe annet…',
    AppStrings.cookWithThis: '🍳 Lag mat med dette',
    AppStrings.lookingClosely: 'Ser nøye etter…',
    AppStrings.fridgeHasPotential: 'Dette kjøleskapet har potensiale.',
    AppStrings.heresWhatYouCanMake: 'Her er hva du kan lage',
    AppStrings.editIngredients: 'Rediger ingredienser',
    AppStrings.scanAgain: 'Skann igjen',
    AppStrings.recipeBadgeFastLazy: 'Raskt og Enkelt',
    AppStrings.recipeBadgeActuallyGood: 'Virkelig Bra',
    AppStrings.recipeBadgeShouldntWork: 'Dette Burde Ikke Fungere',
    AppStrings.share: 'Del',
    AppStrings.settings: 'Innstillinger',
    AppStrings.languageLabel: 'Språk',
    AppStrings.selectLanguage: 'Velg språk',
    AppStrings.clearHistory: 'Tøm historikk',
    AppStrings.historyCleared: 'Historikk tømt',
    AppStrings.about: 'Om',
    AppStrings.aboutTitle: 'Om FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nEn vennlig app for å hjelpe deg med å lage mat med det du har.',
    AppStrings.feedback: 'Tilbakemelding',
    AppStrings.feedbackComingSoon: 'Tilbakemeldingsfunksjon kommer snart',
    AppStrings.privacy: 'Personvern',
    AppStrings.privacyTitle: 'Personvern',
    AppStrings.privacyContent:
        'Bildene dine behandles sikkert og lagres ikke permanent.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historikk',
    AppStrings.emptyHistory: 'Ingen historikk ennå',
    AppStrings.hoursAgo: 'for {hours} timer siden',
    AppStrings.yesterday: 'I går',
    AppStrings.daysAgo: 'for {days} dager siden',
    AppStrings.weekAgo: 'for 1 uke siden',
    AppStrings.weeksAgo: 'for {weeks} uker siden',
  };

  // Romanian translations
  static const Map<String, String> _romanianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Acasă',
    AppStrings.navScan: 'Scanează',
    AppStrings.navHistory: 'Istoric',
    AppStrings.scanMyFridge: 'Scanează frigiderul meu',
    AppStrings.lastResult: 'ULTIMUL REZULTAT',
    AppStrings.recipesFound: '{count} rețete găsite',
    AppStrings.takePhotosHelper: 'Fă 1–3 fotografii. Haosul este în regulă.',
    AppStrings.uploadFromGallery: 'Încarcă din galerie',
    AppStrings.reviewPhotos: 'Revizuiește Fotografiile',
    AppStrings.tapThumbnailToPreview:
        'Atinge o miniatură pentru previzualizare',
    AppStrings.photo: 'fotografie',
    AppStrings.photos: 'fotografii',
    AppStrings.thisIsEnough: 'Este suficient',
    AppStrings.addAnotherPhoto: 'Adaugă altă fotografie',
    AppStrings.confirmIngredients: 'Confirmă Ingredientele',
    AppStrings.heresWhatIThink: 'Iată ce cred că ai.',
    AppStrings.mightBeWrong: 'Pot greși. Corectează orice.',
    AppStrings.addSomethingElse: 'Adaugă altceva…',
    AppStrings.cookWithThis: '🍳 Gătește cu asta',
    AppStrings.lookingClosely: 'Mă uit atent…',
    AppStrings.fridgeHasPotential: 'Acest frigider are potențial.',
    AppStrings.heresWhatYouCanMake: 'Iată ce poți face',
    AppStrings.editIngredients: 'Editează ingredientele',
    AppStrings.scanAgain: 'Scanează din nou',
    AppStrings.recipeBadgeFastLazy: 'Rapid și Ușor',
    AppStrings.recipeBadgeActuallyGood: 'Cu Adevărat Bun',
    AppStrings.recipeBadgeShouldntWork:
        'Acest Lucru Nu Ar Trebui Să Funcționeze',
    AppStrings.share: 'Distribuie',
    AppStrings.settings: 'Setări',
    AppStrings.languageLabel: 'Limbă',
    AppStrings.selectLanguage: 'Selectează limba',
    AppStrings.clearHistory: 'Șterge istoricul',
    AppStrings.historyCleared: 'Istoricul a fost șters',
    AppStrings.about: 'Despre',
    AppStrings.aboutTitle: 'Despre FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nO aplicație prietenoasă pentru a te ajuta să gătești cu ce ai.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Funcția de feedback vine în curând',
    AppStrings.privacy: 'Confidențialitate',
    AppStrings.privacyTitle: 'Confidențialitate',
    AppStrings.privacyContent:
        'Fotografiile tale sunt procesate în siguranță și nu sunt stocate permanent.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Istoric',
    AppStrings.emptyHistory: 'Nu există istoric încă',
    AppStrings.hoursAgo: 'acum {hours} ore',
    AppStrings.yesterday: 'Ieri',
    AppStrings.daysAgo: 'acum {days} zile',
    AppStrings.weekAgo: 'acum 1 săptămână',
    AppStrings.weeksAgo: 'acum {weeks} săptămâni',
  };

  // Swedish translations
  static const Map<String, String> _swedishStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Hem',
    AppStrings.navScan: 'Skanna',
    AppStrings.navHistory: 'Historik',
    AppStrings.scanMyFridge: 'Skanna min kylskåp',
    AppStrings.lastResult: 'SENASTE RESULTAT',
    AppStrings.recipesFound: '{count} recept hittade',
    AppStrings.takePhotosHelper: 'Ta 1–3 foton. Rörigt är okej.',
    AppStrings.uploadFromGallery: 'Ladda upp från galleri',
    AppStrings.reviewPhotos: 'Granska Foton',
    AppStrings.tapThumbnailToPreview:
        'Tryck på en miniatyr för förhandsvisning',
    AppStrings.photo: 'foto',
    AppStrings.photos: 'foton',
    AppStrings.thisIsEnough: 'Detta räcker',
    AppStrings.addAnotherPhoto: 'Lägg till ett annat foto',
    AppStrings.confirmIngredients: 'Bekräfta Ingredienser',
    AppStrings.heresWhatIThink: 'Här är vad jag tror att du har.',
    AppStrings.mightBeWrong: 'Jag kan ha fel. Rätta till vad som helst.',
    AppStrings.addSomethingElse: 'Lägg till något annat…',
    AppStrings.cookWithThis: '🍳 Laga mat med detta',
    AppStrings.lookingClosely: 'Tittar noga…',
    AppStrings.fridgeHasPotential: 'Detta kylskåp har potential.',
    AppStrings.heresWhatYouCanMake: 'Här är vad du kan göra',
    AppStrings.editIngredients: 'Redigera ingredienser',
    AppStrings.scanAgain: 'Skanna igen',
    AppStrings.recipeBadgeFastLazy: 'Snabb & Enkel',
    AppStrings.recipeBadgeActuallyGood: 'Riktigt Bra',
    AppStrings.recipeBadgeShouldntWork: 'Detta Borde Inte Fungera',
    AppStrings.share: 'Dela',
    AppStrings.settings: 'Inställningar',
    AppStrings.languageLabel: 'Språk',
    AppStrings.selectLanguage: 'Välj språk',
    AppStrings.clearHistory: 'Rensa historik',
    AppStrings.historyCleared: 'Historik rensad',
    AppStrings.about: 'Om',
    AppStrings.aboutTitle: 'Om FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nEn vänlig app för att hjälpa dig laga mat med vad du har.',
    AppStrings.feedback: 'Feedback',
    AppStrings.feedbackComingSoon: 'Feedback-funktion kommer snart',
    AppStrings.privacy: 'Integritet',
    AppStrings.privacyTitle: 'Integritet',
    AppStrings.privacyContent:
        'Dina foton bearbetas säkert och lagras inte permanent.',
    AppStrings.ok: 'OK',
    AppStrings.history: 'Historik',
    AppStrings.emptyHistory: 'Ingen historik ännu',
    AppStrings.hoursAgo: 'för {hours} timmar sedan',
    AppStrings.yesterday: 'Igår',
    AppStrings.daysAgo: 'för {days} dagar sedan',
    AppStrings.weekAgo: 'för 1 vecka sedan',
    AppStrings.weeksAgo: 'för {weeks} veckor sedan',
  };

  // Ukrainian translations
  static const Map<String, String> _ukrainianStrings = {
    AppStrings.appName: 'FridgeGPT',
    AppStrings.navHome: 'Головна',
    AppStrings.navScan: 'Сканувати',
    AppStrings.navHistory: 'Історія',
    AppStrings.scanMyFridge: 'Сканувати мій холодильник',
    AppStrings.lastResult: 'ОСТАННІЙ РЕЗУЛЬТАТ',
    AppStrings.recipesFound: 'Знайдено {count} рецептів',
    AppStrings.takePhotosHelper:
        'Зробіть 1–3 фотографії. Безлад – це нормально.',
    AppStrings.uploadFromGallery: 'Завантажити з галереї',
    AppStrings.reviewPhotos: 'Перегляд фотографій',
    AppStrings.tapThumbnailToPreview:
        'Натисніть на мініатюру для попереднього перегляду',
    AppStrings.photo: 'фото',
    AppStrings.photos: 'фотографії',
    AppStrings.thisIsEnough: 'Цього достатньо',
    AppStrings.addAnotherPhoto: 'Додати ще одну фотографію',
    AppStrings.confirmIngredients: 'Підтвердити інгредієнти',
    AppStrings.heresWhatIThink: 'Ось що, я думаю, у вас є.',
    AppStrings.mightBeWrong: 'Я можу помилятися. Виправте що завгодно.',
    AppStrings.addSomethingElse: 'Додати щось інше…',
    AppStrings.cookWithThis: '🍳 Готувати з цим',
    AppStrings.lookingClosely: 'Придивляюся…',
    AppStrings.fridgeHasPotential: 'У цього холодильника є потенціал.',
    AppStrings.heresWhatYouCanMake: 'Ось що ви можете приготувати',
    AppStrings.editIngredients: 'Редагувати інгредієнти',
    AppStrings.scanAgain: 'Сканувати знову',
    AppStrings.recipeBadgeFastLazy: 'Швидко та Просто',
    AppStrings.recipeBadgeActuallyGood: 'Дійсно Добре',
    AppStrings.recipeBadgeShouldntWork: 'Це не повинно працювати',
    AppStrings.share: 'Поділитися',
    AppStrings.settings: 'Налаштування',
    AppStrings.languageLabel: 'Мова',
    AppStrings.selectLanguage: 'Вибрати мову',
    AppStrings.clearHistory: 'Очистити історію',
    AppStrings.historyCleared: 'Історію очищено',
    AppStrings.about: 'Про додаток',
    AppStrings.aboutTitle: 'Про FridgeGPT',
    AppStrings.aboutContent:
        'FridgeGPT v1\n\nДружній додаток, який допоможе вам готувати з того, що у вас є.',
    AppStrings.feedback: 'Відгук',
    AppStrings.feedbackComingSoon: 'Функція відгуків незабаром з\'явиться',
    AppStrings.privacy: 'Конфіденційність',
    AppStrings.privacyTitle: 'Конфіденційність',
    AppStrings.privacyContent:
        'Ваші фотографії обробляються безпечно і не зберігаються постійно.',
    AppStrings.ok: 'ОК',
    AppStrings.history: 'Історія',
    AppStrings.emptyHistory: 'Історії поки немає',
    AppStrings.hoursAgo: '{hours} годин тому',
    AppStrings.yesterday: 'Вчора',
    AppStrings.daysAgo: '{days} днів тому',
    AppStrings.weekAgo: '1 тиждень тому',
    AppStrings.weeksAgo: '{weeks} тижнів тому',
  };
}
