"""
Food image descriptions generated by AI analysis.
Contains descriptions for all 364 food images in 27 languages.
Format: "food name with ingredient1, ingredient2, ingredient3"

Generated by: analyze_food_images.py (English) + translate_food_descriptions.py (multilingual)
Total images: 364 across 9 categories
Languages: 27 (en, ar, bn, zh, da, nl, fi, fr, de, el, he, hi, id, it, ja, ko, no, pl, pt, ro, ru, es, sv, th, tr, uk, vi)
"""

# Import language-specific descriptions from unified language files
from app.services.languages.arabic import FOOD_DESCRIPTIONS_AR
from app.services.languages.bengali import FOOD_DESCRIPTIONS_BN
from app.services.languages.danish import FOOD_DESCRIPTIONS_DA
from app.services.languages.german import FOOD_DESCRIPTIONS_DE
from app.services.languages.greek import FOOD_DESCRIPTIONS_EL
from app.services.languages.english import FOOD_DESCRIPTIONS_EN
from app.services.languages.spanish import FOOD_DESCRIPTIONS_ES
from app.services.languages.finnish import FOOD_DESCRIPTIONS_FI
from app.services.languages.french import FOOD_DESCRIPTIONS_FR
from app.services.languages.hebrew import FOOD_DESCRIPTIONS_HE
from app.services.languages.hindi import FOOD_DESCRIPTIONS_HI
from app.services.languages.indonesian import FOOD_DESCRIPTIONS_ID
from app.services.languages.italian import FOOD_DESCRIPTIONS_IT
from app.services.languages.japanese import FOOD_DESCRIPTIONS_JA
from app.services.languages.korean import FOOD_DESCRIPTIONS_KO
from app.services.languages.dutch import FOOD_DESCRIPTIONS_NL
from app.services.languages.norwegian import FOOD_DESCRIPTIONS_NO
from app.services.languages.polish import FOOD_DESCRIPTIONS_PL
from app.services.languages.portuguese import FOOD_DESCRIPTIONS_PT
from app.services.languages.romanian import FOOD_DESCRIPTIONS_RO
from app.services.languages.russian import FOOD_DESCRIPTIONS_RU
from app.services.languages.swedish import FOOD_DESCRIPTIONS_SV
from app.services.languages.thai import FOOD_DESCRIPTIONS_TH
from app.services.languages.turkish import FOOD_DESCRIPTIONS_TR
from app.services.languages.ukrainian import FOOD_DESCRIPTIONS_UK
from app.services.languages.vietnamese import FOOD_DESCRIPTIONS_VI
from app.services.languages.chinese import FOOD_DESCRIPTIONS_ZH

# Combine all languages into unified structure
# This combines the imported language dictionaries into the expected format
FOOD_DESCRIPTIONS = {}

# Build combined dictionary
for image_path in FOOD_DESCRIPTIONS_EN.keys():
    FOOD_DESCRIPTIONS[image_path] = {
        "ar": FOOD_DESCRIPTIONS_AR.get(image_path, ""),
        "bn": FOOD_DESCRIPTIONS_BN.get(image_path, ""),
        "da": FOOD_DESCRIPTIONS_DA.get(image_path, ""),
        "de": FOOD_DESCRIPTIONS_DE.get(image_path, ""),
        "el": FOOD_DESCRIPTIONS_EL.get(image_path, ""),
        "en": FOOD_DESCRIPTIONS_EN.get(image_path, ""),
        "es": FOOD_DESCRIPTIONS_ES.get(image_path, ""),
        "fi": FOOD_DESCRIPTIONS_FI.get(image_path, ""),
        "fr": FOOD_DESCRIPTIONS_FR.get(image_path, ""),
        "he": FOOD_DESCRIPTIONS_HE.get(image_path, ""),
        "hi": FOOD_DESCRIPTIONS_HI.get(image_path, ""),
        "id": FOOD_DESCRIPTIONS_ID.get(image_path, ""),
        "it": FOOD_DESCRIPTIONS_IT.get(image_path, ""),
        "ja": FOOD_DESCRIPTIONS_JA.get(image_path, ""),
        "ko": FOOD_DESCRIPTIONS_KO.get(image_path, ""),
        "nl": FOOD_DESCRIPTIONS_NL.get(image_path, ""),
        "no": FOOD_DESCRIPTIONS_NO.get(image_path, ""),
        "pl": FOOD_DESCRIPTIONS_PL.get(image_path, ""),
        "pt": FOOD_DESCRIPTIONS_PT.get(image_path, ""),
        "ro": FOOD_DESCRIPTIONS_RO.get(image_path, ""),
        "ru": FOOD_DESCRIPTIONS_RU.get(image_path, ""),
        "sv": FOOD_DESCRIPTIONS_SV.get(image_path, ""),
        "th": FOOD_DESCRIPTIONS_TH.get(image_path, ""),
        "tr": FOOD_DESCRIPTIONS_TR.get(image_path, ""),
        "uk": FOOD_DESCRIPTIONS_UK.get(image_path, ""),
        "vi": FOOD_DESCRIPTIONS_VI.get(image_path, ""),
        "zh": FOOD_DESCRIPTIONS_ZH.get(image_path, ""),
    }
